version: '3.5'
services:
  devapp:
    build:
      context: .
      target: devapp
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    env_file:
      - .env
    ports:
      - ${PORT}:8000
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
    command: poetry run python -m src.entrypoints.fastapi
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - 27017:27017
